# Generated by Django 4.2.9 on 2024-01-25 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Educationsdetails',
        ),
    ]
