# Generated by Django 4.2.9 on 2024-02-02 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0008_description_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='description_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experise_detail', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
