# Generated by Django 4.2.9 on 2024-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_description_user_expertise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.CharField(max_length=20),
        ),
    ]
