# Generated by Django 4.2.9 on 2024-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_description_aboutuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='aboutuser',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
