# Generated by Django 4.2.9 on 2024-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_description_aboutuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='User_description',
            field=models.TextField(default='Describe Something About Yourself', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aboutuser',
            field=models.CharField(default='Describe About Yourself in 2 Lines', max_length=200),
        ),
        migrations.DeleteModel(
            name='description',
        ),
    ]
