# Generated by Django 4.2.9 on 2024-02-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_link_userlink_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='link',
        ),
    ]
