# Generated by Django 4.2.9 on 2024-02-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_profile_user_alter_userlink_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
