# Generated by Django 4.2.9 on 2024-02-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0019_alter_project_description_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_choice', models.CharField(choices=[('1', 'Template 1'), ('2', 'Template 2'), ('3', 'Template 3')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
