# Generated by Django 4.2.9 on 2024-03-02 15:56

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_userprofile_otp_userprofile_otp_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_expiry',
        ),
        migrations.AlterField(
            model_name='templatechoice',
            name='template_choice',
            field=models.CharField(choices=[('1', 'Template 1'), ('2', 'Template 2'), ('3', 'Template 3')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), login.models.validate_photo_size]),
        ),
    ]
