# Generated by Django 4.2.9 on 2024-03-03 03:01

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_remove_userprofile_otp_remove_userprofile_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatechoice',
            name='color_choice',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), login.models.validate_photo_size]),
        ),
    ]
