# Generated by Django 4.2.9 on 2024-03-09 13:03

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_templatechoice_color_choice_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsdetail',
            name='Cgpa',
            field=models.IntegerField(default=9.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationsdetail',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), login.models.validate_photo_size]),
        ),
        migrations.DeleteModel(
            name='expertise',
        ),
    ]
