# Generated by Django 4.2.9 on 2024-03-09 13:07

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_educationsdetail_cgpa_educationsdetail_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsdetail',
            name='Cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), login.models.validate_photo_size]),
        ),
    ]
