# Generated by Django 4.2.9 on 2024-04-13 17:58

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_alter_links_github_alter_links_linkdin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), login.models.validate_photo_size]),
        ),
    ]
